export interface WorldTheme {
  id: string
  name: string
  description: string
  icon: string
  skyColor: number
  fogColor: number
  fogNear: number
  fogFar: number
  ambientIntensity: number
  lightIntensity: number
  lightColor: number
  waterLevel: number
  treeChance: number
  caveIntensity: number
  hostileMobCap: number
  passiveMobCount: number
  dayLength: number
  surfaceBlock: number
  subSurfaceBlock: number
  heightScale: number
  hasClouds: boolean
  extraMobs: string[]
  scareFactor: number
}

export const WORLD_THEMES: WorldTheme[] = [
  {
    id: 'meadow',
    name: 'Sunny Meadows',
    description: 'Peaceful rolling hills, gentle animals, and warm sunshine. Perfect for builders.',
    icon: '🌻',
    skyColor: 0x87ceeb,
    fogColor: 0xb4e0f7,
    fogNear: 60,
    fogFar: 130,
    ambientIntensity: 0.7,
    lightIntensity: 0.9,
    lightColor: 0xffffff,
    waterLevel: 6,
    treeChance: 0.95,
    caveIntensity: 0.55,
    hostileMobCap: 3,
    passiveMobCount: 12,
    dayLength: 900,
    surfaceBlock: 1,
    subSurfaceBlock: 2,
    heightScale: 0.35,
    hasClouds: true,
    extraMobs: [],
    scareFactor: 0,
  },
  {
    id: 'classic',
    name: 'The Overworld',
    description: 'The classic experience. Explore caves, fight monsters at night, mine diamonds.',
    icon: '⛏️',
    skyColor: 0x87ceeb,
    fogColor: 0xb4e0f7,
    fogNear: 50,
    fogFar: 120,
    ambientIntensity: 0.6,
    lightIntensity: 0.8,
    lightColor: 0xffffff,
    waterLevel: 6,
    treeChance: 0.96,
    caveIntensity: 0.58,
    hostileMobCap: 6,
    passiveMobCount: 8,
    dayLength: 600,
    surfaceBlock: 1,
    subSurfaceBlock: 2,
    heightScale: 0.45,
    hasClouds: true,
    extraMobs: [],
    scareFactor: 3,
  },
  {
    id: 'desert',
    name: 'Scorched Dunes',
    description: 'Endless sand under a blazing sun. Water is scarce, dangers hide beneath.',
    icon: '🏜️',
    skyColor: 0xd4a04a,
    fogColor: 0xe8c478,
    fogNear: 40,
    fogFar: 100,
    ambientIntensity: 0.8,
    lightIntensity: 1.0,
    lightColor: 0xffeecc,
    waterLevel: 2,
    treeChance: 0.995,
    caveIntensity: 0.6,
    hostileMobCap: 8,
    passiveMobCount: 3,
    dayLength: 500,
    surfaceBlock: 5,
    subSurfaceBlock: 5,
    heightScale: 0.25,
    hasClouds: false,
    extraMobs: [],
    scareFactor: 4,
  },
  {
    id: 'darkforest',
    name: 'The Whispering Woods',
    description: 'Dense canopy blocks out the sky. Mobs lurk between the trees even during the day.',
    icon: '🌲',
    skyColor: 0x3a5a3a,
    fogColor: 0x2a3a2a,
    fogNear: 15,
    fogFar: 45,
    ambientIntensity: 0.25,
    lightIntensity: 0.3,
    lightColor: 0x88aa88,
    waterLevel: 4,
    treeChance: 0.88,
    caveIntensity: 0.55,
    hostileMobCap: 10,
    passiveMobCount: 4,
    dayLength: 600,
    surfaceBlock: 1,
    subSurfaceBlock: 2,
    heightScale: 0.35,
    hasClouds: false,
    extraMobs: ['creeper'],
    scareFactor: 6,
  },
  {
    id: 'abyss',
    name: 'The Deep Abyss',
    description: 'A shattered world of deep canyons and ravines. Hostile mobs everywhere. Not for the faint of heart.',
    icon: '🕳️',
    skyColor: 0x1a1a2e,
    fogColor: 0x16213e,
    fogNear: 10,
    fogFar: 40,
    ambientIntensity: 0.15,
    lightIntensity: 0.2,
    lightColor: 0x6666aa,
    waterLevel: 8,
    treeChance: 0.99,
    caveIntensity: 0.7,
    hostileMobCap: 15,
    passiveMobCount: 1,
    dayLength: 300,
    surfaceBlock: 3,
    subSurfaceBlock: 3,
    heightScale: 0.65,
    hasClouds: false,
    extraMobs: ['creeper', 'skeleton'],
    scareFactor: 8,
  },
  {
    id: 'nether',
    name: 'The Nether Wastes',
    description: 'A hellish dimension of fire and darkness. No daylight. Maximum hostility. Eternal night.',
    icon: '🔥',
    skyColor: 0x330000,
    fogColor: 0x440000,
    fogNear: 10,
    fogFar: 35,
    ambientIntensity: 0.2,
    lightIntensity: 0.15,
    lightColor: 0xff4400,
    waterLevel: 0,
    treeChance: 1.0,
    caveIntensity: 0.72,
    hostileMobCap: 20,
    passiveMobCount: 0,
    dayLength: 99999,
    surfaceBlock: 8,
    subSurfaceBlock: 3,
    heightScale: 0.5,
    hasClouds: false,
    extraMobs: ['zombie', 'skeleton', 'creeper'],
    scareFactor: 10,
  },
  {
    id: 'sky',
    name: 'Cloud Kingdom',
    description: 'Floating islands in the sky. Fall and it\'s over. Build bridges between the peaks.',
    icon: '☁️',
    skyColor: 0xaaddff,
    fogColor: 0xcceeFF,
    fogNear: 30,
    fogFar: 80,
    ambientIntensity: 0.8,
    lightIntensity: 0.9,
    lightColor: 0xffffff,
    waterLevel: 0,
    treeChance: 0.94,
    caveIntensity: 0.75,
    hostileMobCap: 2,
    passiveMobCount: 6,
    dayLength: 800,
    surfaceBlock: 1,
    subSurfaceBlock: 2,
    heightScale: 0.6,
    hasClouds: true,
    extraMobs: [],
    scareFactor: 2,
  },
]

export function getThemeById(id: string): WorldTheme {
  return WORLD_THEMES.find(t => t.id === id) ?? WORLD_THEMES[1]
}
